# Generated by Django 5.1 on 2024-08-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('start_of_month', models.DateField()),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_reports', models.IntegerField()),
                ('average_report', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_count', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('complainant_id', models.IntegerField()),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
