# Generated by Django 5.1 on 2024-08-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scamreport',
            table='scam_report',
        ),
    ]
