# Generated by Django 5.1 on 2024-08-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0003_alter_scamreport_start_of_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamCategory',
            fields=[
                ('category_level_2', models.CharField(max_length=100)),
                ('category_level_3', models.CharField(max_length=100)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scam_category',
            },
        ),
    ]
