# Generated by Django 5.1 on 2024-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0005_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='scam_contact_mode',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
