# Generated by Django 5.1 on 2024-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0006_scamreport_scam_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='scam_contact_mode',
            field=models.CharField(max_length=100),
        ),
    ]
