# Generated by Django 5.1 on 2024-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0007_alter_scamreport_scam_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='amount_lost',
            field=models.IntegerField(db_column='Amount_lost'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='average_loss',
            field=models.IntegerField(db_column='Average_loss'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='average_report',
            field=models.IntegerField(db_column='Average_report'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='category_id',
            field=models.IntegerField(db_column='Category_ID'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='complainant_id',
            field=models.IntegerField(db_column='Complainant_ID'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='group_count',
            field=models.IntegerField(db_column='Group_Count'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='number_of_reports',
            field=models.IntegerField(db_column='Number_of_reports'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='report_id',
            field=models.AutoField(db_column='Report_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='scam_contact_mode',
            field=models.CharField(db_column='Scam_Contact_Mode', max_length=100),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='start_of_month',
            field=models.CharField(db_column='StartOfMonth', max_length=100),
        ),
    ]
