# Generated by Django 5.1 on 2024-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currentScams', '0008_alter_scamreport_amount_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainant',
            name='complainant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scamcategory',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='report_id',
            field=models.IntegerField(db_column='Report_ID', primary_key=True, serialize=False),
        ),
    ]
